name: Prisma Migrate

on:
 push:
  branches: [ci-db]
#  paths:
#    - "./prisma/**/*.*"

jobs:
  install:
    runs-on: ubuntu-latest
    
    steps:
      - name: Setup Nodejs
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 19.x
          cache: "npm"
      - name: Install
        run: npm install
      - name: Rerun Install
        run: npm install
        
  generate:
    runs-on: ubuntu-latest
    
    steps:
      - name: Setup Nodejs
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 19.x
          cache: "npm"
      - name: Install
        run: npm install

      - run: rm -rf node_modules/.prisma

      - name: Generate Prisma Client
        run: npx prisma generate
        
  migrate:
    runs-on: ubuntu-latest 
    
    steps:
      - name: Setup Nodejs
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 19.x
          cache: "npm"
      - name: Install
        run: npm install
    
      - name: Deploy Migrations
        run: npx prisma migrate deploy
        env:
          DATABASE_URL: ${{ secrets.PROD_DATABASE_URL }}
